name: Dispatch API tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rest-api-tests:
    uses: ./.github/workflows/rest-api-tests.yml
    secrets: inherit

  soap-api-tests:
    uses: ./.github/workflows/soap-api-tests.yml
    secrets: inherit

  graph-api-tests:
    uses: ./.github/workflows/service-graph.yml
    secrets: inherit

  grpc-api-tests:
    uses: ./.github/workflows/grpc-api-tests.yml
    secrets: inherit
